spring:
  application:
    name: gyullectric

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계에서는 update, 운영 시에는 validate 또는 none 권장
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    gyullectric.gyullectric.util.PredictionClient: debug

custom:
  prediction-api:
    url: http://localhost:5000/predict
